name: (DEPRECATED) Legacy Auto Format

# Este workflow foi substituído por format-unified.yml e foi mantido apenas
# como stub documental. Não possui gatilhos automáticos.
on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Aviso
        run: |
          echo "Este workflow é legado. Use .github/workflows/format-unified.yml"
