name: Docstring Format

on: [push, pull_request]

jobs:
  docformatter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install docformatter ruff
      - name: Docformatter check
        id: df
        run: |
          set +e
          docformatter --check --recursive --wrap-summaries 100 --wrap-descriptions 100 .
          if [ $? -ne 0 ]; then echo "needs_fix=true" >> $GITHUB_OUTPUT; else echo "needs_fix=false" >> $GITHUB_OUTPUT; fi
          exit 0
      - name: Apply docformatter (push only)
        if: steps.df.outputs.needs_fix == 'true' && github.event_name == 'push'
        run: |
          docformatter --in-place --recursive --wrap-summaries 100 --wrap-descriptions 100 .
      - name: Commit changes
        if: steps.df.outputs.needs_fix == 'true' && github.event_name == 'push'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git diff --cached --quiet || git commit -m "chore: formatar docstrings"
          git push || true
      - name: PR Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: docformatter
          message: |
            ${{ steps.df.outputs.needs_fix == 'true' && '⚠️ Docstrings fora do padrão.' || '✅ Docstrings formatadas.' }}
