name: Unified Formatting

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache Python deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Cache Node deps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('.prettierrc*', 'package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install black ruff docformatter
          npm install --global prettier@3 prettier-plugin-sh@0.13.1
      - name: Run Black (apply on push)
        id: black
        run: |
          if black --check .; then echo "needs=false" >> $GITHUB_OUTPUT; else echo "needs=true" >> $GITHUB_OUTPUT; fi
        continue-on-error: true
      - name: Apply Black
        if: steps.black.outputs.needs == 'true' && github.event_name == 'push'
        run: black .
      - name: Run docformatter
        run: |
          docformatter --in-place --recursive --wrap-summaries 100 --wrap-descriptions 100 .
      - name: Run Prettier (check)
        id: prettier
        run: |
          set +e
          prettier --check "**/*.{md,yml,yaml,json}" || echo "needs_formatting=true" >> $GITHUB_OUTPUT
          exit 0
      - name: Apply Prettier
        if: github.event_name == 'push'
        run: |
          prettier --write "**/*.{md,yml,yaml,json}"
      - name: Format code blocks in Markdown
        run: |
          python scripts/format_markdown_code_blocks.py || true
      - name: Commit changes
        if: github.event_name == 'push'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git diff --cached --quiet || git commit -m "chore: unified formatting"
          git push || true
      - name: PR Comment Summary
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: unified-format
          message: |
            Formatação unificada executada. Verifique diffs. Arquivos podem ser atualizados automaticamente em pushes para branch principal.
