name: Broken Links

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --exclude-mail --max-concurrency 8 ./**/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
