name: AI PR Summary

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-summary:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Get diff
        id: diff
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1 || true
          git diff --unified=0 origin/${{ github.base_ref }}...HEAD > pr_diff.txt
          echo "file=pr_diff.txt" >> $GITHUB_OUTPUT
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai==0.8.3 requests
      - name: Generate summary
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DIFF_FILE: ${{ steps.diff.outputs.file }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_FULL: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/gemini_pr_summary.py
