name: (DEPRECATED) Legacy Prettier Format

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Aviso
        run: echo "Este workflow foi substituído por format-unified.yml"
