name: Spell Check

on: [push, pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: true
          ignore_words_list: crate,ser
          skip: ./.git,./.mypy_cache,./.ruff_cache
